#!/usr/bin/env python3
"""Embed corpus .pptx binaries as generated MoonBit test sources.

Emits one `src/integration/corpus_<slug>_embed_test.mbt` per configured
corpus file, holding the file's bytes as fixed-width base64 chunks plus
an accessor decoding them via `corpus_bytes` (hand-written in
`corpus_test.mbt`). Embedding real Office output into the blackbox test
package lets `moon test` prove reader losslessness on every backend
without file I/O (TODO.md §4.2, ADR-011 Tier-1 follow-up).

Run from the repo root (no arguments; stdlib only):

    python3 tools/embed-corpus/gen.py

Re-run whenever `FILES` below or the corpus files change, then commit
the regenerated `.mbt` files alongside.
"""

import base64
import hashlib
import pathlib

# (corpus file, slug) — keep "a few": every entry costs ~1.4x its size
# in committed source and compiles on four backends.
FILES = [
    ("testPPT.pptx", "testppt"),
    ("table_test.pptx", "table_test"),
    ("with_japanese.pptx", "with_japanese"),
]

CHUNK = 72  # base64 chars per array element; keeps lines fmt-friendly

REPO = pathlib.Path(__file__).resolve().parents[2]
CORPUS = REPO / "test_fixtures" / "corpus"
OUT_DIR = REPO / "src" / "integration"

HEADER = """\
// GENERATED by tools/embed-corpus/gen.py — DO NOT EDIT.
//
// Embedded copy of `test_fixtures/corpus/{name}`
// ({size} bytes, sha256 {sha}).
// Provenance: Apache POI test data, Apache-2.0 — see
// test_fixtures/corpus/SOURCES.md. Decoded at test time by
// `corpus_bytes` (corpus_test.mbt) so `moon test` exercises the read
// path on real Office output on every backend (TODO.md §4.2, ADR-011
// Tier-1 follow-up).

///|
/// Byte length of the original `{name}`.
let corpus_{slug}_len : Int = {size}

///|
/// `{name}` as fixed-width base64 chunks.
let corpus_{slug}_b64 : Array[String] = [
{chunks}]

///|
/// The raw bytes of `test_fixtures/corpus/{name}`.
fn corpus_{slug}() -> FixedArray[Byte] {{
  corpus_bytes(corpus_{slug}_b64, corpus_{slug}_len)
}}
"""


def emit(name: str, slug: str) -> None:
    data = (CORPUS / name).read_bytes()
    b64 = base64.b64encode(data).decode("ascii")
    chunks = "".join(
        f'  "{b64[i : i + CHUNK]}",\n' for i in range(0, len(b64), CHUNK)
    )
    out = OUT_DIR / f"corpus_{slug}_embed_test.mbt"
    out.write_text(
        HEADER.format(
            name=name,
            slug=slug,
            size=len(data),
            sha=hashlib.sha256(data).hexdigest(),
            chunks=chunks,
        )
    )
    print(f"{out.relative_to(REPO)}: {len(data)} bytes -> {len(b64)} b64 chars")


if __name__ == "__main__":
    for name, slug in FILES:
        emit(name, slug)
